# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cec5f99cf9f1bc5a01f1b04c863db763ac7d183aa5eb3b115f6f1ed37962909d111ee3141378a33b3185b32d9f135dcb1318daa82d6c144ba3db19fcd69c066

test:
  secret_key_base: 2cb6fcc57c0a549ab34066d4e5a6cb3e838b5a8035453b164b1d95123157360149a5708d8c0c8e4fa5a83d75c3882aff882b932cdfb35c1beec77c0e41b21029

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
